### ISSUE TITLE
Will fail when used on resultsets with HRI set for inflation

### ISSUE THREAD

**Issue by ribasushi** [oalders/data-printer-filter-dbix-class#1]
[This line](https://metacpan.org/source/OALDERS/Data-Printer-Filter-DBIx-Class-0.000001/lib/Data/Printer/Filter/DBIx/Class.pm#L21) assumes you always get DBIx::Class::Core objects from $rs->next. This is hardly the case. Also I'd check for `while (defined ... )`, as it is possible that objects have oddball bool overloading.

**Comment by oalders** [comment]
Ok, that was fast. :rocket:  I shall fix. :)
